In [ ]:
#use of numpy 
#image processing 
#import numpy as np - importing numpy 
#array object in numpy is  ndarray


In [2]:
import numpy as np 
list = [1,2,3,[4,5]]
print (list)

[1, 2, 3, [4, 5]]


In [12]:
# np.array(list)
h = [[4,3],[1,2],[3,7]]
n = np.array(h)
n.shape
n.size
t=n.transpose()
t.size
t.shape

(2, 3)

In [13]:
n = np.array([1,5.5])
n.dtype


dtype('float64')

In [14]:
np.array([1,"1",2.5,3,4,5])


array(['1', '1', '2.5', '3', '4', '5'], dtype='<U32')

In [19]:
a = np.empty((4,2), dtype= str)
print(a)

[['' '']
 ['' '']
 ['' '']
 ['' '']]


In [17]:
b = np.empty((5,1),dtype = int)
print(b)

[[4607182418800017408]
 [4613374868287651840]
 [4618441417868443648]
 [4622241330054037504]
 [4625478292286210048]]


In [53]:
a = np.ones((4,2), dtype ="bool")
print(a)

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


In [22]:
a.flatten()

array(['', '', '', '', '', '', '', ''], dtype='<U1')

In [34]:
arr = np.arange(5,19)
arr
# arr1 = np.arange(5,19,2)
# arr1
r= arr.reshape(2,7)
arr
r[0:,1:]

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18]])

In [35]:
x = np.array([[1,2,3,4,5],[6,7,8,9,0]])
y = np.array([[10,20,35,46,53],[63,74,87,9,20]])


In [36]:
np.add(x,y)

array([[11, 22, 38, 50, 58],
       [69, 81, 95, 18, 20]])

In [37]:
np.multiply(x,y)

array([[ 10,  40, 105, 184, 265],
       [378, 518, 696,  81,   0]])

In [40]:
np.subtract(x,y)

array([[ -9, -18, -32, -42, -48],
       [-57, -67, -79,   0, -20]])

In [39]:
np.divide(x,y)

array([[0.1       , 0.1       , 0.08571429, 0.08695652, 0.09433962],
       [0.0952381 , 0.09459459, 0.09195402, 1.        , 0.        ]])

In [43]:
z = np.ones([5,5],dtype=int)
x.dot(z)

array([[15, 15, 15, 15, 15],
       [30, 30, 30, 30, 30]])

In [45]:
x.max()

9

In [48]:
x.min()

0

In [46]:
x.sum()

45

In [47]:
np.sum(x,axis = 1) #if axis = 0 we get the sum of columns 

array([15, 30])

In [49]:
np.char.center('Hi', 4, '*')



array('*Hi*', dtype='<U4')

In [50]:
print(np.char.center('Hi', 4, '*'))

*Hi*


In [51]:
np.mean(x)

4.5

In [52]:
np.sqrt(x) #returns the sqrt of each value 


array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 0.        ]])

In [56]:
np.std(x)  #return the standard deviation  of all the elements     


2.8722813232690143

In [58]:
np.log(x)  #returns the log values  

/var/folders/zr/dk__m8955c98g4zbr120vmg40000gn/T/ipykernel_42752/1070253399.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)  #returns the log values


array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458,       -inf]])

In [60]:
np.pi #importing pi using numpy 

3.141592653589793

In [61]:
np.sin(x)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,  0.        ]])

In [62]:
np.cos(x)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026,  1.        ]])

In [64]:
from numpy import random as rand   #imporitng a specific class/ package from numpy 

In [65]:
import numpy as np 

In [69]:
np.random.random(24) # 24 is the no of elements you want in your nd array 
#only generates float type arrays 

array([0.6074769 , 0.77724283, 0.09899817, 0.12514646, 0.82308357,
       0.58805427, 0.40714759, 0.58966471, 0.97222323, 0.65905168,
       0.04848394, 0.05313186, 0.1957278 , 0.01866161, 0.26333335,
       0.71046009, 0.60046091, 0.08844612, 0.44438933, 0.44050759,
       0.7367762 , 0.79906916, 0.57465378, 0.50670873])

In [71]:
np.random.random([2,3,4])  # having 2 rows 3 columns and having 4 values in each 

array([[[0.49735492, 0.82951977, 0.13617209, 0.87838691],
        [0.82948525, 0.819707  , 0.75873576, 0.26716191],
        [0.47900861, 0.73284242, 0.90421675, 0.23287754]],

       [[0.74640036, 0.88595024, 0.02748884, 0.77871489],
        [0.54496075, 0.45433995, 0.47344518, 0.00928927],
        [0.70771903, 0.20436577, 0.32551935, 0.41049171]]])

In [77]:
a= np.random.random(24)
b =np.sqrt(a[5:]) 
print(b)

print(b.size)

[0.65399965 0.83141906 0.88627404 0.53302814 0.92203868 0.51982145
 0.40798559 0.90943546 0.36353846 0.92754961 0.99566772 0.98984705
 0.83126653 0.83130192 0.32417991 0.91158309 0.57735916 0.64012805
 0.80402869]
19


In [78]:
from numpy import random as rand

In [79]:
rand.random(29)

array([0.38944732, 0.21403621, 0.22678296, 0.32825593, 0.82056575,
       0.29687597, 0.07364569, 0.11696968, 0.94637896, 0.88905172,
       0.68349146, 0.18780928, 0.58655698, 0.43874806, 0.64972784,
       0.7058835 , 0.09423526, 0.28290865, 0.85399883, 0.08711472,
       0.37695022, 0.74442469, 0.47527519, 0.03817577, 0.99316215,
       0.23674495, 0.76098187, 0.49177583, 0.73133583])

In [85]:
np.random.randint(2,10,(2,4))

array([[3, 3, 8, 5],
       [3, 2, 3, 2]])

In [86]:
np.random.rand(27)

array([0.18867765, 0.8112047 , 0.91091656, 0.62569438, 0.51314149,
       0.86312997, 0.75325619, 0.81645076, 0.3090085 , 0.14040298,
       0.94476118, 0.71650107, 0.14754678, 0.58766943, 0.63343955,
       0.66859753, 0.95519739, 0.88067971, 0.94285598, 0.94217631,
       0.15786105, 0.79460015, 0.33095704, 0.71853206, 0.33051089,
       0.6185059 , 0.20044973])

In [91]:
np.random.rand(4,5) # 4 rows and 5 columns  # only generates positive values 

array([[0.55504924, 0.99586226, 0.92534166, 0.67761684, 0.21017494],
       [0.21665154, 0.92790787, 0.1296948 , 0.8193748 , 0.56100539],
       [0.19449429, 0.51950204, 0.18646556, 0.56471735, 0.13061025],
       [0.59389208, 0.05923199, 0.13042917, 0.19762105, 0.91782362]])

In [90]:
np.random.randn(4,5)  #randn generates negative values 

array([[-0.47798898,  0.16932514, -0.01445543, -2.0846985 ,  0.68005918],
       [-0.64554229,  0.37395108,  0.23793326,  1.02733637, -0.72993106],
       [-1.49139555,  0.11858586, -0.70842164,  0.81486205, -1.35645065],
       [-0.57868983,  1.37474171, -1.95320836,  0.68132904,  0.6781182 ]])

In [94]:
np.char.center('Hi', 4, '*')
print(np.char.center('Hi', 20, '*'))  #generates a string with filler characters and the given string in the middle '*' is a filler character 

*********Hi*********


In [98]:
s = "snfff ffffff"
print(np.char.center(s, 20, '*'))
print(np.char.upper(s))
print(np.char.split(" "))

****snfff ffffff****
SNFFF FFFFFF
[]


PANDAS  

In [99]:
import pandas as pd

In [101]:

e = pd.Series([]) # only contain a single row of data but can store any data type 
print(e)

Series([], dtype: object)


In [102]:
print(type(e))

<class 'pandas.core.series.Series'>


In [105]:
s=pd.Series([1,2,3,4,5,6.7,'1'])
print(s)

0      1
1      2
2      3
3      4
4      5
5    6.7
6      1
dtype: object


In [106]:
s[1:3]  #slicing panda series  1 is the starting index and 3 is the max limit 3rd index will not be shown

1    2
2    3
dtype: object

In [108]:
s= pd.Series([1,2,3,4], index=['A','B','C','D'], name = "Numbers")
s['A':'B']

A    1
B    2
Name: Numbers, dtype: int64

In [109]:
s = pd.Series('5', index=[4,5,6,7,8]) #value 5 is stored in all index 
print(s) #scalar value series 

4    5
5    5
6    5
7    5
8    5
dtype: object


In [110]:
df = pd.DataFrame([[1,2,3,4],[11,22,33,44]])
print(df)

    0   1   2   3
0   1   2   3   4
1  11  22  33  44


In [111]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [112]:
df.size

8

In [113]:
df.shape

(2, 4)

In [114]:
print(df.rename(index={0:'W'})) #renaming index row 

    0   1   2   3
W   1   2   3   4
1  11  22  33  44


In [115]:
df= pd.DataFrame([[1,2,3,4],[11,22,33,44]], index=['X','Y'])
print(df)

    0   1   2   3
X   1   2   3   4
Y  11  22  33  44


In [117]:
df = df.rename(index={'X':'W'})
print(df)

    0   1   2   3
W   1   2   3   4
Y  11  22  33  44


In [118]:
print(df.reset_index())

  index   0   1   2   3
0     W   1   2   3   4
1     Y  11  22  33  44


In [122]:
df.reset_index(inplace=True, drop=True) # to remove previous index values implace is used to change the current data frame
print(df)

    0   1   2   3
0   1   2   3   4
1  11  22  33  44


In [123]:
df = pd.DataFrame([{'a':1,'b':2},{'c':11, 'b':22}])
print(df)

     a   b     c
0  1.0   2   NaN
1  NaN  22  11.0


In [126]:
df.rename(columns={'c':'z'}, inplace=True)
#rename(index, columns, inplace)
print(df)

     a   b     z
0  1.0   2   NaN
1  NaN  22  11.0


In [133]:
df1 = pd.DataFrame({'RollNo':[1,2,3,4],'Phy':[1,5,6,3]})
df2 = pd.DataFrame({'RollNo':[1,2,3,5],'Chem':[4,5,3,5]})
df = pd.merge(df1,df2)
# df = pd.merge(df1,df2, on="RollNo", how="inner")
# df = pd.merge(df1,df2, on="RollNo", how="right")
# df = pd.merge(df1,df2, on="RollNo", how="outer")

print(df)

   RollNo  Phy  Chem
0       1  1.0   4.0
1       2  5.0   5.0
2       3  6.0   3.0
3       4  3.0   NaN
4       5  NaN   5.0


In [140]:
# df3 = df1._append(df2)
df3 = df1._append(df2, ignore_index=True)
print(df3)

   RollNo  Phy  Chem
0       1  1.0   NaN
1       2  5.0   NaN
2       3  6.0   NaN
3       4  3.0   NaN
4       1  NaN   4.0
5       2  NaN   5.0
6       3  NaN   3.0
7       5  NaN   5.0


In [137]:
df1

RollNo  Phy
0       1    1
1       2    5
2       3    6
3       4    3

Importing a CSV file 

In [ ]:
import pandas as pd 
import io
# from google.colab import files
# data = files.upload()
df = pd.read_csv('sample.csv')
df

In [ ]:
df = pd.read_csv('sample.csv')
df.tail()

In [ ]:
df.columns

In [ ]:
df.describe

In [ ]:
df.info()

In [ ]:
df.isnull()

In [ ]:
df.isnull().sum()

In [ ]:
df2=df.dropna()
df2